name: Goimports Lint
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  generate-check:
    name: Verify
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Setup private repo
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"

      - name: Install tools
        run: |
          go install github.com/incu6us/goimports-reviser/v3@latest

      - name: Format imports
        run: make lint-imports

      - name: Verify goimports
        run: |
          git diff --exit-code || { echo "Error: Goimports are not up to date."; exit 1; }
