name: Golang Linter
# Lint runs golangci-lint over the entire CometBFT repository.
#
# This workflow is run on every pull request and push to v0.38.x.
#
# The `golangci` job will pass without running if no *.{go, mod, sum}
# files have been modified.
#
# To run this locally, simply run `make lint` from the root of the repo.

on:
  pull_request:
    paths:
      - "**.go"
  push:
    paths:
      - "**.go"
    branches:
      - dev
jobs:
  golangci:
    name: golangci-lint
    runs-on: [ "self-hosted", "Linux", "X64", "ci" ]
    timeout-minutes: 8
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
    steps:
      - uses: actions/checkout@v4
      - name: private
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
        if: env.GIT_DIFF
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.GH_TOKEN }}
        if: env.GIT_DIFF
